name: 发布到PyPI

on:
  release:
    types: [created]
  # 也可以手动触发
  workflow_dispatch:

jobs:
  deploy:
    name: 构建并发布到PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # 用于PyPI发布
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
      
      - name: 构建包
        run: python -m build
      
      - name: 检查包
        run: |
          pip install twine
          twine check dist/*
      
      - name: 发布到PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # 可选项：使用测试PyPI
        # with:
        #   repository-url: https://test.pypi.org/legacy/ 