name: 安全扫描

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # 每周一 UTC 2:00

jobs:
  scan:
    name: 依赖安全扫描
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install safety
      
      - name: 生成依赖列表
        run: |
          pip install .
          pip freeze > requirements-lock.txt
      
      - name: 运行安全扫描
        run: safety check -r requirements-lock.txt
      
  codeql:
    name: CodeQL分析
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: 初始化 CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      
      - name: 执行 CodeQL 分析
        uses: github/codeql-action/analyze@v3 